# Generated by Django 3.1.3 on 2023-04-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidvaccinemanagement', '0003_patient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctorId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
