# Generated by Django 3.1.3 on 2023-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidvaccinemanagement', '0004_auto_20230426_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptiondetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('PrescriptionDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctorId',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patientId',
        ),
    ]
