# Generated by Django 3.1.3 on 2023-04-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidvaccinemanagement', '0005_auto_20230426_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptiondetails',
            old_name='PrescriptionDate',
            new_name='prescriptionDate',
        ),
    ]
