# Generated by Django 3.1.3 on 2023-04-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidvaccinemanagement', '0006_auto_20230426_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccineappointmentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('emailid', models.EmailField(max_length=254)),
                ('vaccine', models.CharField(choices=[('Covaxin', 'Covaxin'), ('Covishield', 'Covishield'), ('Covo-vax', 'Covo-vax'), ('Sputnik', 'Sputnik'), ('ZyCoV-D', 'ZyCoV-D')], default='Covaxin', max_length=40)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
