# Generated by Django 3.1.3 on 2023-04-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidvaccinemanagement', '0008_auto_20230429_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineappointmentdetails',
            name='date',
            field=models.DateField(),
        ),
    ]
