# Generated by Django 3.1.3 on 2023-05-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidvaccinemanagement', '0009_auto_20230429_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineappointmentdetails',
            name='date',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='vaccineappointmentdetails',
            name='emailid',
            field=models.EmailField(max_length=254, verbose_name=''),
        ),
    ]
