# Generated by Django 3.1.3 on 2023-05-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidvaccinemanagement', '0010_auto_20230501_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineappointmentdetails',
            name='patientId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
